name: Prod build trigger

on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify Build Hook
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          curl -X POST -d '{}' "${NETLIFY_BUILD_HOOK_URL}?trigger_branch=main&trigger_title=Triggered+by+documentation+merge+to+main&clear_cache=true"
