name: "Prod deploy"

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: "Trigger prod deploy from main app"
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: questdb/questdb.io
          event-type: docs-updated
